# Generated by Django 5.0.6 on 2025-02-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=100)),
                ('description', models.TextField()),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_icon', models.CharField(default='lnr lnr-icon-phone-handset', max_length=50)),
                ('phone_title', models.CharField(default='Call Us On', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_icon', models.CharField(default='lnr lnr-icon-envelope1', max_length=50)),
                ('email_title', models.CharField(default='Mail to Us', max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FooterCopyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer/logo/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Newsletter', max_length=100)),
                ('description', models.TextField()),
                ('placeholder_text', models.CharField(default='Your Email', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FooterServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Services', max_length=100)),
                ('links', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FooterUsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Useful Links', max_length=100)),
                ('links', models.JSONField(default=list)),
            ],
        ),
    ]
