# Generated by Django 5.0.6 on 2025-02-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_footeraboutsection_footercontactinfo_footercopyright_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+36 55 540 069', max_length=20)),
                ('email', models.EmailField(default='info@example.com', max_length=254)),
                ('working_hours', models.CharField(default='Mon - Sat 8:00 - 6:30, Sunday - CLOSED', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderTopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='1901 Horidge Cir. Shiloh, Hawaii 81063', max_length=200)),
                ('working_hours', models.CharField(default='Mon - Fri: 09.00am - 10.00 pm', max_length=100)),
                ('email', models.EmailField(default='info@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderUsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy_link', models.URLField(blank=True, null=True)),
                ('faq_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
