# Generated by Django 5.0.6 on 2025-02-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_headercontactinfo_headersociallinks_headertopinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='header/logo/')),
                ('logo_alt_text', models.CharField(default='Logifix', max_length=100)),
                ('logo_link', models.URLField(default='/')),
            ],
        ),
    ]
