# Generated by Django 5.0.6 on 2025-02-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_headerlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_centers', models.IntegerField(default=541)),
                ('years_experience', models.IntegerField(default=35)),
                ('countries_regions', models.IntegerField(default=147)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('background_image', models.ImageField(upload_to='about/hero/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='WHO WE ARE', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('years_experience', models.IntegerField(default=25)),
                ('image_1', models.ImageField(upload_to='about/')),
                ('image_2', models.ImageField(upload_to='about/')),
                ('logo_image', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Why select us', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('background_image', models.ImageField(upload_to='about/background/')),
                ('promo_image', models.ImageField(upload_to='about/promo/')),
                ('promo_title', models.CharField(max_length=200)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.CharField(default='kg', max_length=20)),
            ],
        ),
    ]
