# Generated by Django 5.0.6 on 2025-02-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_aboutcounter_aboutpagehero_aboutsection_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Contact Us', max_length=200)),
                ('hero_background_image', models.ImageField(upload_to='contact/hero/')),
                ('form_title', models.CharField(default='Feel free to write', max_length=200)),
                ('form_subtitle', models.CharField(default='Send us email', max_length=200)),
                ('contact_info_title', models.CharField(default='Get in touch with us', max_length=200)),
                ('contact_info_subtitle', models.CharField(default='Need any help?', max_length=200)),
                ('contact_info_description', models.TextField(default='Lorem ipsum is simply free text available dolor sit amet consectetur notted adipisicing elit sed do eiusmod tempor incididunt simply dolore magna.')),
                ('phone_title', models.CharField(default='Have any question?', max_length=100)),
                ('phone_number', models.CharField(default='+92 (020)-9850', max_length=20)),
                ('email_title', models.CharField(default='Write email', max_length=100)),
                ('email_address', models.EmailField(default='needhelp@company.com', max_length=254)),
                ('address_title', models.CharField(default='Visit anytime', max_length=100)),
                ('address', models.CharField(default='66 broklyn golden street. New York', max_length=200)),
                ('google_map_embed_url', models.TextField(default='https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=1%20Grafton%20Street,%20Dublin,%20Ireland+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed')),
            ],
        ),
    ]
