# Generated by Django 5.0.6 on 2025-02-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='text_1',
            field=models.CharField(default='Worldwide service', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='text_2',
            field=models.CharField(default='24/7 Support', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='Safety and Reliability', max_length=200),
        ),
    ]
