# Generated by Django 5.0.6 on 2025-02-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_service_description_service_text_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='flaticon-team', max_length=50),
        ),
    ]
