# Generated by Django 5.0.6 on 2025-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_service_contact_phone_service_contact_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_badge_title', models.CharField(default='TRUSTED BY', max_length=100)),
                ('banner_badge_count', models.IntegerField(default=10)),
                ('banner_main_title', models.CharField(default='Transport Solution 24/7', max_length=200)),
                ('banner_subtitle', models.TextField(default='We strongly support best practice sharing across our operations around the world and across various')),
                ('banner_background_image', models.ImageField(upload_to='homepage/banner/')),
                ('banner_button_text', models.CharField(default='Request A Quote', max_length=100)),
                ('about_subtitle', models.CharField(default='Who we are', max_length=100)),
                ('about_title', models.CharField(default='We Provide Full Range Logistics Solution', max_length=200)),
                ('about_description', models.TextField(default='Our operations around the world and across various transporation sectors.')),
                ('about_experience_years', models.IntegerField(default=25)),
                ('about_experience_description', models.TextField(default='With over four decades of experience providing solutions to large-scale enterprises throughout the globe we offer end-to-end logistics.')),
                ('about_checkmark_1', models.CharField(default='With over four decades of experience', max_length=200)),
                ('about_checkmark_2', models.CharField(default='Every pleasure is to be welcomed and every pain', max_length=200)),
                ('about_checkmark_3', models.CharField(default='Velit esse cillum dolore eu fugiat nulla pariatur', max_length=200)),
                ('about_image_1', models.ImageField(upload_to='homepage/about/')),
                ('about_image_2', models.ImageField(upload_to='homepage/about/')),
                ('why_choose_subtitle', models.CharField(default='WHY CHOOSE US', max_length=100)),
                ('why_choose_title', models.CharField(default='We create opportunity to reach potential', max_length=200)),
                ('why_choose_description', models.TextField(default='There are many variations of passages of available but majority have suffered alteration in some form.')),
                ('why_choose_promo_title', models.CharField(default='Fast Shipping', max_length=200)),
                ('why_choose_promo_image', models.ImageField(upload_to='homepage/why-choose/')),
                ('why_choose_starting_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('cta_title', models.CharField(default='Logistics & Cargo For Business', max_length=200)),
                ('cta_background_image', models.ImageField(upload_to='homepage/cta/')),
                ('cta_video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
