# Generated by Django 5.0.6 on 2025-02-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_remove_homepagecontent_why_choose_promo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontactinfo',
            name='background_image',
            field=models.ImageField(default='images/icons/footer-bg.png', upload_to='footer/logo/'),
        ),
    ]
