# Generated by Django 5.0.6 on 2025-02-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_footercontactinfo_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercontactinfo',
            name='email_icon',
        ),
        migrations.RemoveField(
            model_name='footercontactinfo',
            name='phone_icon',
        ),
        migrations.RemoveField(
            model_name='footerlogo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='headercontactinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='headercontactinfo',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='headerlogo',
            name='logo_link',
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='about_page',
            field=models.CharField(default='About', max_length=100),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='contact_page',
            field=models.CharField(default='Contact', max_length=100),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='home_page',
            field=models.CharField(default='Home', max_length=100),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='services_page',
            field=models.CharField(default='Services', max_length=100),
        ),
        migrations.AlterField(
            model_name='footerservices',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
