# Generated by Django 5.0.6 on 2025-02-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_remove_footercontactinfo_email_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_1',
            field=models.CharField(default='Distribution Center', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_2',
            field=models.CharField(default='Years Of Experience', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_3',
            field=models.CharField(default='Countries and Regions', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text',
            field=models.CharField(default='Explore more', max_length=200),
        ),
    ]
