# Generated by Django 5.0.6 on 2025-02-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_aboutcounter_counter_title_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='button_text',
            field=models.CharField(default='Get Started Now', max_length=200),
        ),
    ]
