# Generated by Django 5.0.6 on 2025-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_whychooseus_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='services_page_title',
            field=models.CharField(default='Services', max_length=200),
        ),
    ]
