# Generated by Django 5.0.6 on 2025-02-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_service_services_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='services_background_image',
            field=models.ImageField(default='images/background/page-title.jpg', upload_to='services/'),
        ),
    ]
