# Generated by Django 5.0.6 on 2025-02-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_service_services_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='center_title',
            field=models.CharField(default='Service Center', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_title',
            field=models.CharField(default='Service Overview', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='service_details_background_image',
            field=models.ImageField(default='images/background/page-title.jpg', upload_to='services/details'),
        ),
    ]
