# Generated by Django 5.0.6 on 2025-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_homepagecontent_banner_badge_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Website title', max_length=255)),
                ('favicon', models.ImageField(default='images/favicon.png', help_text='Upload favicon image', upload_to='favicons/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='caption_icon',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature_block_one_icon',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature_block_two_icon',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='caption_title',
            field=models.CharField(default='Moving Your Products accross border', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_image_man',
            field=models.ImageField(default='images/resource/why-choose3-1.png', upload_to='homepage/cta/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='banner_badge_text',
            field=models.CharField(default='Fast and Reliable Shipping', max_length=100),
        ),
    ]
