# Generated by Django 5.0.6 on 2025-02-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_sitesettings_remove_homepagecontent_caption_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.CharField(blank=True, help_text='Add your site description here (150-160 characters optimal)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(help_text='Website title', max_length=150),
        ),
    ]
