# Generated by Django 5.0.6 on 2025-02-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_sitesettings_description_sitesettings_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertopinfo',
            name='customers_page',
            field=models.CharField(default='Customers', max_length=100),
        ),
    ]
