# Generated by Django 5.0.6 on 2025-02-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_headertopinfo_customers_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='background_image',
            field=models.ImageField(default='images/background/page-title.jpg', upload_to='clients/'),
        ),
        migrations.AddField(
            model_name='client',
            name='page_title',
            field=models.CharField(default='Customers', max_length=200),
        ),
    ]
