# Generated by Django 5.0.6 on 2025-02-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_remove_client_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_type',
            field=models.CharField(choices=[('international', 'International Company'), ('local', 'Local Company')], default='local', max_length=20),
        ),
    ]
