# Generated by Django 5.0.6 on 2025-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_client_company_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='client',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
