# Generated by Django 5.0.6 on 2025-02-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_alter_client_options_client_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(default='images/background/page-title.jpg', upload_to='clients/')),
                ('page_title', models.CharField(default='Customers', max_length=200)),
            ],
        ),
    ]
