# Generated by Django 5.0.6 on 2025-02-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_customerspagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar_dz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ckb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_af',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ar',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ar_dz',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ast',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_az',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_be',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_bg',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_bn',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_br',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_bs',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ca',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ckb',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_cs',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_cy',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_da',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_de',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_dsb',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_el',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_en',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_en_au',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_en_gb',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_eo',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_es',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_es_ar',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_es_co',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_es_mx',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_es_ni',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_es_ve',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_et',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_eu',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_fa',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_fi',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_fr',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_fy',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ga',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_gd',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_gl',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_he',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_hi',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_hr',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_hsb',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_hu',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_hy',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ia',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ig',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ind',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_io',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_is',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_it',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ja',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ka',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_kab',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_kk',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_km',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_kn',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ko',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ky',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_lb',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_lt',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_lv',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_mk',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ml',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_mn',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_mr',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ms',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_my',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_nb',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ne',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_nl',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_nn',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_os',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_pa',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_pl',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_pt',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_pt_br',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ro',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ru',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_sk',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_sl',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_sq',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_sr',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_sr_latn',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_sv',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_sw',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ta',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_te',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_tg',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_th',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_tk',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_tr',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_tt',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_udm',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ug',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_uk',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_ur',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_uz',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_vi',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_zh_hans',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='description_zh_hant',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing.', null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_af',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ar',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ar_dz',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ast',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_az',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_be',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_bg',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_bn',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_br',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_bs',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ca',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ckb',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_cs',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_cy',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_da',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_de',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_dsb',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_el',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_en',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_en_au',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_en_gb',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_eo',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_es',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_es_ar',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_es_co',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_es_mx',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_es_ni',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_es_ve',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_et',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_eu',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_fa',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_fi',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_fr',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_fy',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ga',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_gd',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_gl',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_he',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_hi',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_hr',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_hsb',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_hu',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_hy',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ia',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ig',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ind',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_io',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_is',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_it',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ja',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ka',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_kab',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_kk',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_km',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_kn',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ko',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ky',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_lb',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_lt',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_lv',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_mk',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ml',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_mn',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_mr',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ms',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_my',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_nb',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ne',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_nl',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_nn',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_os',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_pa',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_pl',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_pt',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_pt_br',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ro',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ru',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_sk',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_sl',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_sq',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_sr',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_sr_latn',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_sv',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_sw',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ta',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_te',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_tg',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_th',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_tk',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_tr',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_tt',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_udm',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ug',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_uk',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ur',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_uz',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_vi',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_zh_hans',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_zh_hant',
            field=models.CharField(default='Frequently Asked Questions', max_length=200, null=True),
        ),
    ]
