# Generated by Django 5.0.6 on 2025-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_remove_faq_answer_af_remove_faq_answer_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_1_az',
            field=models.CharField(default='Distribution Center', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_1_en',
            field=models.CharField(default='Distribution Center', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_1_ru',
            field=models.CharField(default='Distribution Center', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_2_az',
            field=models.CharField(default='Years Of Experience', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_2_en',
            field=models.CharField(default='Years Of Experience', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_2_ru',
            field=models.CharField(default='Years Of Experience', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_3_az',
            field=models.CharField(default='Countries and Regions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_3_en',
            field=models.CharField(default='Countries and Regions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutcounter',
            name='counter_title_3_ru',
            field=models.CharField(default='Countries and Regions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagehero',
            name='title_az',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagehero',
            name='title_en',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagehero',
            name='title_ru',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text_az',
            field=models.CharField(default='Explore more', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text_en',
            field=models.CharField(default='Explore more', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text_ru',
            field=models.CharField(default='Explore more', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle_az',
            field=models.CharField(default='WHO WE ARE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle_en',
            field=models.CharField(default='WHO WE ARE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle_ru',
            field=models.CharField(default='WHO WE ARE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_az',
            field=models.CharField(default='66 broklyn golden street. New York', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_en',
            field=models.CharField(default='66 broklyn golden street. New York', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_ru',
            field=models.CharField(default='66 broklyn golden street. New York', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_title_az',
            field=models.CharField(default='Visit anytime', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_title_en',
            field=models.CharField(default='Visit anytime', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_title_ru',
            field=models.CharField(default='Visit anytime', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_description_az',
            field=models.TextField(default='Lorem ipsum is simply free text available dolor sit amet consectetur notted adipisicing elit sed do eiusmod tempor incididunt simply dolore magna.', null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_description_en',
            field=models.TextField(default='Lorem ipsum is simply free text available dolor sit amet consectetur notted adipisicing elit sed do eiusmod tempor incididunt simply dolore magna.', null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_description_ru',
            field=models.TextField(default='Lorem ipsum is simply free text available dolor sit amet consectetur notted adipisicing elit sed do eiusmod tempor incididunt simply dolore magna.', null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_subtitle_az',
            field=models.CharField(default='Need any help?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_subtitle_en',
            field=models.CharField(default='Need any help?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_subtitle_ru',
            field=models.CharField(default='Need any help?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_title_az',
            field=models.CharField(default='Get in touch with us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_title_en',
            field=models.CharField(default='Get in touch with us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_title_ru',
            field=models.CharField(default='Get in touch with us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_title_az',
            field=models.CharField(default='Write email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_title_en',
            field=models.CharField(default='Write email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email_title_ru',
            field=models.CharField(default='Write email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_subtitle_az',
            field=models.CharField(default='Send us email', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_subtitle_en',
            field=models.CharField(default='Send us email', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_subtitle_ru',
            field=models.CharField(default='Send us email', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_title_az',
            field=models.CharField(default='Feel free to write', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_title_en',
            field=models.CharField(default='Feel free to write', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_title_ru',
            field=models.CharField(default='Feel free to write', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_az',
            field=models.CharField(default='Contact Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_en',
            field=models.CharField(default='Contact Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_ru',
            field=models.CharField(default='Contact Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_title_az',
            field=models.CharField(default='Have any question?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_title_en',
            field=models.CharField(default='Have any question?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_title_ru',
            field=models.CharField(default='Have any question?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerspagesettings',
            name='page_title_az',
            field=models.CharField(default='Customers', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerspagesettings',
            name='page_title_en',
            field=models.CharField(default='Customers', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerspagesettings',
            name='page_title_ru',
            field=models.CharField(default='Customers', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footeraboutsection',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footeraboutsection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footeraboutsection',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footeraboutsection',
            name='title_az',
            field=models.CharField(default='About Us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footeraboutsection',
            name='title_en',
            field=models.CharField(default='About Us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footeraboutsection',
            name='title_ru',
            field=models.CharField(default='About Us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='email_title_az',
            field=models.CharField(default='Mail to Us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='email_title_en',
            field=models.CharField(default='Mail to Us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='email_title_ru',
            field=models.CharField(default='Mail to Us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='phone_title_az',
            field=models.CharField(default='Call Us On', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='phone_title_en',
            field=models.CharField(default='Call Us On', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footercontactinfo',
            name='phone_title_ru',
            field=models.CharField(default='Call Us On', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footercopyright',
            name='text_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footercopyright',
            name='text_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footercopyright',
            name='text_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='placeholder_text_az',
            field=models.CharField(default='Your Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='placeholder_text_en',
            field=models.CharField(default='Your Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='placeholder_text_ru',
            field=models.CharField(default='Your Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='title_az',
            field=models.CharField(default='Newsletter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='title_en',
            field=models.CharField(default='Newsletter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footernewsletter',
            name='title_ru',
            field=models.CharField(default='Newsletter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerservices',
            name='title_az',
            field=models.CharField(default='Services', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerservices',
            name='title_en',
            field=models.CharField(default='Services', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerservices',
            name='title_ru',
            field=models.CharField(default='Services', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerusefullinks',
            name='title_az',
            field=models.CharField(default='Useful Links', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerusefullinks',
            name='title_en',
            field=models.CharField(default='Useful Links', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerusefullinks',
            name='title_ru',
            field=models.CharField(default='Useful Links', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headerlogo',
            name='logo_alt_text_az',
            field=models.CharField(default='Logifix', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headerlogo',
            name='logo_alt_text_en',
            field=models.CharField(default='Logifix', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headerlogo',
            name='logo_alt_text_ru',
            field=models.CharField(default='Logifix', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='about_page_az',
            field=models.CharField(default='About', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='about_page_en',
            field=models.CharField(default='About', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='about_page_ru',
            field=models.CharField(default='About', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='address_az',
            field=models.CharField(default='1901 Horidge Cir. Shiloh, Hawaii 81063', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='address_en',
            field=models.CharField(default='1901 Horidge Cir. Shiloh, Hawaii 81063', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='address_ru',
            field=models.CharField(default='1901 Horidge Cir. Shiloh, Hawaii 81063', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='contact_page_az',
            field=models.CharField(default='Contact', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='contact_page_en',
            field=models.CharField(default='Contact', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='contact_page_ru',
            field=models.CharField(default='Contact', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='customers_page_az',
            field=models.CharField(default='Customers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='customers_page_en',
            field=models.CharField(default='Customers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='customers_page_ru',
            field=models.CharField(default='Customers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='home_page_az',
            field=models.CharField(default='Home', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='home_page_en',
            field=models.CharField(default='Home', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='home_page_ru',
            field=models.CharField(default='Home', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='services_page_az',
            field=models.CharField(default='Services', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='services_page_en',
            field=models.CharField(default='Services', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='services_page_ru',
            field=models.CharField(default='Services', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='working_hours_az',
            field=models.CharField(default='Mon - Fri: 09.00am - 10.00 pm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='working_hours_en',
            field=models.CharField(default='Mon - Fri: 09.00am - 10.00 pm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headertopinfo',
            name='working_hours_ru',
            field=models.CharField(default='Mon - Fri: 09.00am - 10.00 pm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_1_az',
            field=models.CharField(default='With over four decades of experience', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_1_en',
            field=models.CharField(default='With over four decades of experience', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_1_ru',
            field=models.CharField(default='With over four decades of experience', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_2_az',
            field=models.CharField(default='Every pleasure is to be welcomed and every pain', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_2_en',
            field=models.CharField(default='Every pleasure is to be welcomed and every pain', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_2_ru',
            field=models.CharField(default='Every pleasure is to be welcomed and every pain', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_3_az',
            field=models.CharField(default='Velit esse cillum dolore eu fugiat nulla pariatur', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_3_en',
            field=models.CharField(default='Velit esse cillum dolore eu fugiat nulla pariatur', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_checkmark_3_ru',
            field=models.CharField(default='Velit esse cillum dolore eu fugiat nulla pariatur', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_description_az',
            field=models.TextField(default='Our operations around the world and across various transporation sectors.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_description_en',
            field=models.TextField(default='Our operations around the world and across various transporation sectors.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_description_ru',
            field=models.TextField(default='Our operations around the world and across various transporation sectors.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_experience_description_az',
            field=models.TextField(default='With over four decades of experience providing solutions to large-scale enterprises throughout the globe we offer end-to-end logistics.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_experience_description_en',
            field=models.TextField(default='With over four decades of experience providing solutions to large-scale enterprises throughout the globe we offer end-to-end logistics.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_experience_description_ru',
            field=models.TextField(default='With over four decades of experience providing solutions to large-scale enterprises throughout the globe we offer end-to-end logistics.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_subtitle_az',
            field=models.CharField(default='Who we are', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_subtitle_en',
            field=models.CharField(default='Who we are', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_subtitle_ru',
            field=models.CharField(default='Who we are', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_title_az',
            field=models.CharField(default='We Provide Full Range Logistics Solution', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_title_en',
            field=models.CharField(default='We Provide Full Range Logistics Solution', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_title_ru',
            field=models.CharField(default='We Provide Full Range Logistics Solution', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_badge_text_az',
            field=models.CharField(default='Fast and Reliable Shipping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_badge_text_en',
            field=models.CharField(default='Fast and Reliable Shipping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_badge_text_ru',
            field=models.CharField(default='Fast and Reliable Shipping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_badge_title_az',
            field=models.CharField(default='TRUSTED BY', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_badge_title_en',
            field=models.CharField(default='TRUSTED BY', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_badge_title_ru',
            field=models.CharField(default='TRUSTED BY', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_button_text_az',
            field=models.CharField(default='Request A Quote', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_button_text_en',
            field=models.CharField(default='Request A Quote', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_button_text_ru',
            field=models.CharField(default='Request A Quote', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_main_title_az',
            field=models.CharField(default='Transport Solution 24/7', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_main_title_en',
            field=models.CharField(default='Transport Solution 24/7', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_main_title_ru',
            field=models.CharField(default='Transport Solution 24/7', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_subtitle_az',
            field=models.TextField(default='We strongly support best practice sharing across our operations around the world and across various', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_subtitle_en',
            field=models.TextField(default='We strongly support best practice sharing across our operations around the world and across various', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='banner_subtitle_ru',
            field=models.TextField(default='We strongly support best practice sharing across our operations around the world and across various', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='button_text_az',
            field=models.CharField(default='Explore More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='button_text_en',
            field=models.CharField(default='Explore More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='button_text_ru',
            field=models.CharField(default='Explore More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='caption_title_az',
            field=models.CharField(default='Moving Your Products accross border', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='caption_title_en',
            field=models.CharField(default='Moving Your Products accross border', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='caption_title_ru',
            field=models.CharField(default='Moving Your Products accross border', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='counter_title_az',
            field=models.CharField(default='Trusted by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='counter_title_en',
            field=models.CharField(default='Trusted by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='counter_title_ru',
            field=models.CharField(default='Trusted by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_title_az',
            field=models.CharField(default='Logistics & Cargo For Business', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_title_en',
            field=models.CharField(default='Logistics & Cargo For Business', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_title_ru',
            field=models.CharField(default='Logistics & Cargo For Business', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_one_text_az',
            field=models.TextField(default='Aenean placerat ut lacus nec pulvinar. Donce eu leo ante at commodo diam dolor sit amet', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_one_text_en',
            field=models.TextField(default='Aenean placerat ut lacus nec pulvinar. Donce eu leo ante at commodo diam dolor sit amet', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_one_text_ru',
            field=models.TextField(default='Aenean placerat ut lacus nec pulvinar. Donce eu leo ante at commodo diam dolor sit amet', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_one_title_az',
            field=models.CharField(default='Safety and Reliability', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_one_title_en',
            field=models.CharField(default='Safety and Reliability', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_one_title_ru',
            field=models.CharField(default='Safety and Reliability', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_two_text_az',
            field=models.TextField(default='Aenean placerat ut lacus nec pulvinar. Donce eu leo ante at commodo diam dolor sit amet', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_two_text_en',
            field=models.TextField(default='Aenean placerat ut lacus nec pulvinar. Donce eu leo ante at commodo diam dolor sit amet', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_two_text_ru',
            field=models.TextField(default='Aenean placerat ut lacus nec pulvinar. Donce eu leo ante at commodo diam dolor sit amet', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_two_title_az',
            field=models.CharField(default='Shipping Worldwide', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_two_title_en',
            field=models.CharField(default='Shipping Worldwide', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='feature_block_two_title_ru',
            field=models.CharField(default='Shipping Worldwide', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_1_az',
            field=models.CharField(default='Urgent transport solutions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_1_en',
            field=models.CharField(default='Urgent transport solutions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_1_ru',
            field=models.CharField(default='Urgent transport solutions', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_2_az',
            field=models.CharField(default='Top quality services with reasonable price', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_2_en',
            field=models.CharField(default='Top quality services with reasonable price', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_2_ru',
            field=models.CharField(default='Top quality services with reasonable price', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_3_az',
            field=models.CharField(default='Reliable & experienced staffs', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_3_en',
            field=models.CharField(default='Reliable & experienced staffs', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='list_item_3_ru',
            field=models.CharField(default='Reliable & experienced staffs', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_description_az',
            field=models.TextField(default='There are many variations of passages of Lorem Ipsum available, but the majority have readable content suffered alteration in some form', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_description_en',
            field=models.TextField(default='There are many variations of passages of Lorem Ipsum available, but the majority have readable content suffered alteration in some form', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_description_ru',
            field=models.TextField(default='There are many variations of passages of Lorem Ipsum available, but the majority have readable content suffered alteration in some form', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_subtitle_az',
            field=models.CharField(default='SPECIAL LOGISTICS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_subtitle_en',
            field=models.CharField(default='SPECIAL LOGISTICS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_subtitle_ru',
            field=models.CharField(default='SPECIAL LOGISTICS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_title_az',
            field=models.CharField(default='Best services for Businesses', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_title_en',
            field=models.CharField(default='Best services for Businesses', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='offer_title_ru',
            field=models.CharField(default='Best services for Businesses', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_description_az',
            field=models.TextField(default='There are many variations of passages of available but majority have suffered alteration in some form.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_description_en',
            field=models.TextField(default='There are many variations of passages of available but majority have suffered alteration in some form.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_description_ru',
            field=models.TextField(default='There are many variations of passages of available but majority have suffered alteration in some form.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_subtitle_az',
            field=models.CharField(default='WHY CHOOSE US', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_subtitle_en',
            field=models.CharField(default='WHY CHOOSE US', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_subtitle_ru',
            field=models.CharField(default='WHY CHOOSE US', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_title_az',
            field=models.CharField(default='We create opportunity to reach potential', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_title_en',
            field=models.CharField(default='We create opportunity to reach potential', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_title_ru',
            field=models.CharField(default='We create opportunity to reach potential', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='center_title_az',
            field=models.CharField(default='Service Center', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='center_title_en',
            field=models.CharField(default='Service Center', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='center_title_ru',
            field=models.CharField(default='Service Center', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_text_az',
            field=models.CharField(default='Need help? Talk to an expert', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_text_en',
            field=models.CharField(default='Need help? Talk to an expert', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_text_ru',
            field=models.CharField(default='Need help? Talk to an expert', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_title_az',
            field=models.CharField(default='Contact with us for any advice', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_title_en',
            field=models.CharField(default='Contact with us for any advice', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='contact_title_ru',
            field=models.CharField(default='Contact with us for any advice', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_az',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing...', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_en',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing...', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_ru',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing...', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_title_az',
            field=models.CharField(default='Service Overview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_title_en',
            field=models.CharField(default='Service Overview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_title_ru',
            field=models.CharField(default='Service Overview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_center_text_az',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing...', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_center_text_en',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing...', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_center_text_ru',
            field=models.TextField(default='Lorem ipsum is simply free text used by copytyping refreshing...', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='services_page_title_az',
            field=models.CharField(default='Services', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='services_page_title_en',
            field=models.CharField(default='Services', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='services_page_title_ru',
            field=models.CharField(default='Services', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_1_az',
            field=models.CharField(default='Worldwide service', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_1_en',
            field=models.CharField(default='Worldwide service', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_1_ru',
            field=models.CharField(default='Worldwide service', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_2_az',
            field=models.CharField(default='24/7 Support', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_2_en',
            field=models.CharField(default='24/7 Support', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='text_2_ru',
            field=models.CharField(default='24/7 Support', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(default='Safety and Reliability', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default='Safety and Reliability', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(default='Safety and Reliability', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_az',
            field=models.CharField(blank=True, help_text='Add your site description here (150-160 characters optimal)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_en',
            field=models.CharField(blank=True, help_text='Add your site description here (150-160 characters optimal)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_ru',
            field=models.CharField(blank=True, help_text='Add your site description here (150-160 characters optimal)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_az',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='title_az',
            field=models.CharField(help_text='Website title', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='title_en',
            field=models.CharField(help_text='Website title', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='title_ru',
            field=models.CharField(help_text='Website title', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='button_text_az',
            field=models.CharField(default='Get Started Now', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='button_text_en',
            field=models.CharField(default='Get Started Now', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='button_text_ru',
            field=models.CharField(default='Get Started Now', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='promo_title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='promo_title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='promo_title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_az',
            field=models.CharField(default='Why select us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_en',
            field=models.CharField(default='Why select us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='subtitle_ru',
            field=models.CharField(default='Why select us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
